accounts:
  - name: user1
    coins: ["10000000000uusd", "100000000stake"]
  - name: user2
    coins: ["10000000000uusd"]
validator:
  name: user1
  staked: "100000000stake"
genesis:
  chain_id: "asset-chain"
  app_state:
    asset:
      assets: [
        {
          denom: "gold",
          total_supply: "1000000",
          oracle_script_id: "2"
        }
      ]
init:
  home: "/Users/nat/.asset-chain"
servers:
  api-address: "localhost:1317"
  grpc-address: "localhost:26657"
