// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: asset/packet.proto

package types

import (
	fmt "fmt"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type AssetOrder struct {
	OrderId      string `protobuf:"bytes,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	OrderType    string `protobuf:"bytes,2,opt,name=order_type,json=orderType,proto3" json:"order_type,omitempty"`
	Addr         string `protobuf:"bytes,3,opt,name=addr,proto3" json:"addr,omitempty"`
	Denom        string `protobuf:"bytes,4,opt,name=denom,proto3" json:"denom,omitempty"`
	PricePerUnit uint64 `protobuf:"varint,5,opt,name=price_per_unit,json=pricePerUnit,proto3" json:"price_per_unit,omitempty"`
	Amount       uint64 `protobuf:"varint,6,opt,name=amount,proto3" json:"amount,omitempty"`
	Status       string `protobuf:"bytes,7,opt,name=status,proto3" json:"status,omitempty"`
	StatusLog    string `protobuf:"bytes,8,opt,name=status_log,json=statusLog,proto3" json:"status_log,omitempty"`
}

func (m *AssetOrder) Reset()         { *m = AssetOrder{} }
func (m *AssetOrder) String() string { return proto.CompactTextString(m) }
func (*AssetOrder) ProtoMessage()    {}
func (*AssetOrder) Descriptor() ([]byte, []int) {
	return fileDescriptor_ae2b96752a4e188c, []int{0}
}
func (m *AssetOrder) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *AssetOrder) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_AssetOrder.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *AssetOrder) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AssetOrder.Merge(m, src)
}
func (m *AssetOrder) XXX_Size() int {
	return m.Size()
}
func (m *AssetOrder) XXX_DiscardUnknown() {
	xxx_messageInfo_AssetOrder.DiscardUnknown(m)
}

var xxx_messageInfo_AssetOrder proto.InternalMessageInfo

func (m *AssetOrder) GetOrderId() string {
	if m != nil {
		return m.OrderId
	}
	return ""
}

func (m *AssetOrder) GetOrderType() string {
	if m != nil {
		return m.OrderType
	}
	return ""
}

func (m *AssetOrder) GetAddr() string {
	if m != nil {
		return m.Addr
	}
	return ""
}

func (m *AssetOrder) GetDenom() string {
	if m != nil {
		return m.Denom
	}
	return ""
}

func (m *AssetOrder) GetPricePerUnit() uint64 {
	if m != nil {
		return m.PricePerUnit
	}
	return 0
}

func (m *AssetOrder) GetAmount() uint64 {
	if m != nil {
		return m.Amount
	}
	return 0
}

func (m *AssetOrder) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *AssetOrder) GetStatusLog() string {
	if m != nil {
		return m.StatusLog
	}
	return ""
}

func init() {
	proto.RegisterType((*AssetOrder)(nil), "songwongtp.asset.asset.AssetOrder")
}

func init() { proto.RegisterFile("asset/packet.proto", fileDescriptor_ae2b96752a4e188c) }

var fileDescriptor_ae2b96752a4e188c = []byte{
	// 289 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x44, 0x90, 0xcd, 0x4a, 0x03, 0x31,
	0x14, 0x85, 0x1b, 0xed, 0x6f, 0x10, 0x17, 0xa1, 0x94, 0x28, 0x38, 0x14, 0x71, 0xd1, 0x8d, 0xcd,
	0xc2, 0x27, 0xd0, 0x5d, 0x41, 0x50, 0x8a, 0x6e, 0xdc, 0x0c, 0xd3, 0x49, 0x48, 0x83, 0x36, 0x37,
	0x24, 0x19, 0xb4, 0x6f, 0xe1, 0x63, 0xb9, 0xec, 0xd2, 0xa5, 0x74, 0xf0, 0x3d, 0x24, 0x37, 0x05,
	0x37, 0xe1, 0x9c, 0xf3, 0x5d, 0xc2, 0xbd, 0x87, 0xb2, 0x2a, 0x04, 0x15, 0x85, 0xab, 0xea, 0x57,
	0x15, 0xe7, 0xce, 0x43, 0x04, 0x36, 0x09, 0x60, 0xf5, 0x3b, 0x58, 0x1d, 0xdd, 0x1c, 0x71, 0x7e,
	0xcf, 0xc7, 0x1a, 0x34, 0xe0, 0x88, 0x48, 0x2a, 0x4f, 0x5f, 0xfe, 0x12, 0x4a, 0x6f, 0x13, 0x7f,
	0xf0, 0x52, 0x79, 0x76, 0x46, 0x87, 0x90, 0x44, 0x69, 0x24, 0x27, 0x53, 0x32, 0x1b, 0x2d, 0x07,
	0xe8, 0x17, 0x92, 0x5d, 0x50, 0x9a, 0x51, 0xdc, 0x3a, 0xc5, 0x8f, 0x10, 0x8e, 0x30, 0x79, 0xda,
	0x3a, 0xc5, 0x18, 0xed, 0x56, 0x52, 0x7a, 0x7e, 0x8c, 0x00, 0x35, 0x1b, 0xd3, 0x9e, 0x54, 0x16,
	0x36, 0xbc, 0x8b, 0x61, 0x36, 0xec, 0x8a, 0x9e, 0x3a, 0x6f, 0x6a, 0x55, 0x3a, 0xe5, 0xcb, 0xc6,
	0x9a, 0xc8, 0x7b, 0x53, 0x32, 0xeb, 0x2e, 0x4f, 0x30, 0x7d, 0x54, 0xfe, 0xd9, 0x9a, 0xc8, 0x26,
	0xb4, 0x5f, 0x6d, 0xa0, 0xb1, 0x91, 0xf7, 0x91, 0x1e, 0x5c, 0xca, 0x43, 0xac, 0x62, 0x13, 0xf8,
	0x00, 0x3f, 0x3d, 0xb8, 0xb4, 0x5e, 0x56, 0xe5, 0x1b, 0x68, 0x3e, 0xcc, 0xeb, 0xe5, 0xe4, 0x1e,
	0xf4, 0xdd, 0xe2, 0x6b, 0x5f, 0x90, 0xdd, 0xbe, 0x20, 0x3f, 0xfb, 0x82, 0x7c, 0xb6, 0x45, 0x67,
	0xd7, 0x16, 0x9d, 0xef, 0xb6, 0xe8, 0xbc, 0x08, 0x6d, 0xe2, 0xba, 0x59, 0xcd, 0x6b, 0xd8, 0x88,
	0xff, 0xea, 0x04, 0x96, 0x76, 0x5d, 0xaf, 0x2b, 0x63, 0xc5, 0x47, 0x76, 0x22, 0x5d, 0x1e, 0x56,
	0x7d, 0x6c, 0xee, 0xe6, 0x2f, 0x00, 0x00, 0xff, 0xff, 0x99, 0xe6, 0x72, 0x6e, 0x7d, 0x01, 0x00,
	0x00,
}

func (m *AssetOrder) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *AssetOrder) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *AssetOrder) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.StatusLog) > 0 {
		i -= len(m.StatusLog)
		copy(dAtA[i:], m.StatusLog)
		i = encodeVarintPacket(dAtA, i, uint64(len(m.StatusLog)))
		i--
		dAtA[i] = 0x42
	}
	if len(m.Status) > 0 {
		i -= len(m.Status)
		copy(dAtA[i:], m.Status)
		i = encodeVarintPacket(dAtA, i, uint64(len(m.Status)))
		i--
		dAtA[i] = 0x3a
	}
	if m.Amount != 0 {
		i = encodeVarintPacket(dAtA, i, uint64(m.Amount))
		i--
		dAtA[i] = 0x30
	}
	if m.PricePerUnit != 0 {
		i = encodeVarintPacket(dAtA, i, uint64(m.PricePerUnit))
		i--
		dAtA[i] = 0x28
	}
	if len(m.Denom) > 0 {
		i -= len(m.Denom)
		copy(dAtA[i:], m.Denom)
		i = encodeVarintPacket(dAtA, i, uint64(len(m.Denom)))
		i--
		dAtA[i] = 0x22
	}
	if len(m.Addr) > 0 {
		i -= len(m.Addr)
		copy(dAtA[i:], m.Addr)
		i = encodeVarintPacket(dAtA, i, uint64(len(m.Addr)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.OrderType) > 0 {
		i -= len(m.OrderType)
		copy(dAtA[i:], m.OrderType)
		i = encodeVarintPacket(dAtA, i, uint64(len(m.OrderType)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.OrderId) > 0 {
		i -= len(m.OrderId)
		copy(dAtA[i:], m.OrderId)
		i = encodeVarintPacket(dAtA, i, uint64(len(m.OrderId)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintPacket(dAtA []byte, offset int, v uint64) int {
	offset -= sovPacket(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *AssetOrder) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.OrderId)
	if l > 0 {
		n += 1 + l + sovPacket(uint64(l))
	}
	l = len(m.OrderType)
	if l > 0 {
		n += 1 + l + sovPacket(uint64(l))
	}
	l = len(m.Addr)
	if l > 0 {
		n += 1 + l + sovPacket(uint64(l))
	}
	l = len(m.Denom)
	if l > 0 {
		n += 1 + l + sovPacket(uint64(l))
	}
	if m.PricePerUnit != 0 {
		n += 1 + sovPacket(uint64(m.PricePerUnit))
	}
	if m.Amount != 0 {
		n += 1 + sovPacket(uint64(m.Amount))
	}
	l = len(m.Status)
	if l > 0 {
		n += 1 + l + sovPacket(uint64(l))
	}
	l = len(m.StatusLog)
	if l > 0 {
		n += 1 + l + sovPacket(uint64(l))
	}
	return n
}

func sovPacket(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozPacket(x uint64) (n int) {
	return sovPacket(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *AssetOrder) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowPacket
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: AssetOrder: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: AssetOrder: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field OrderId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPacket
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthPacket
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthPacket
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.OrderId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field OrderType", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPacket
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthPacket
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthPacket
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.OrderType = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Addr", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPacket
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthPacket
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthPacket
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Addr = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Denom", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPacket
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthPacket
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthPacket
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Denom = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field PricePerUnit", wireType)
			}
			m.PricePerUnit = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPacket
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.PricePerUnit |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 6:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Amount", wireType)
			}
			m.Amount = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPacket
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Amount |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Status", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPacket
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthPacket
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthPacket
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Status = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 8:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field StatusLog", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPacket
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthPacket
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthPacket
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.StatusLog = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipPacket(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthPacket
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipPacket(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowPacket
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowPacket
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowPacket
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthPacket
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupPacket
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthPacket
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthPacket        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowPacket          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupPacket = fmt.Errorf("proto: unexpected end of group")
)
