// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: asset/query.proto

package types

import (
	context "context"
	fmt "fmt"
	_ "github.com/cosmos/cosmos-sdk/types/query"
	_ "github.com/gogo/protobuf/gogoproto"
	grpc1 "github.com/gogo/protobuf/grpc"
	proto "github.com/gogo/protobuf/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// QueryAssetInfoRequest is the request type for the Query/AssetInfo RPC method
type QueryAssetInfoRequest struct {
	// denom is the asset denom to query info for
	Denom string `protobuf:"bytes,1,opt,name=denom,proto3" json:"denom,omitempty"`
}

func (m *QueryAssetInfoRequest) Reset()         { *m = QueryAssetInfoRequest{} }
func (m *QueryAssetInfoRequest) String() string { return proto.CompactTextString(m) }
func (*QueryAssetInfoRequest) ProtoMessage()    {}
func (*QueryAssetInfoRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_4785ee6dd031b7c8, []int{0}
}
func (m *QueryAssetInfoRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryAssetInfoRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryAssetInfoRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryAssetInfoRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryAssetInfoRequest.Merge(m, src)
}
func (m *QueryAssetInfoRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryAssetInfoRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryAssetInfoRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryAssetInfoRequest proto.InternalMessageInfo

// QueryAssetInfoResponse is the response type for the Query/AssetInfo RPC method
type QueryAssetInfoResponse struct {
	// asset is the asset info of the denom
	Asset *Asset `protobuf:"bytes,1,opt,name=asset,proto3" json:"asset,omitempty"`
}

func (m *QueryAssetInfoResponse) Reset()         { *m = QueryAssetInfoResponse{} }
func (m *QueryAssetInfoResponse) String() string { return proto.CompactTextString(m) }
func (*QueryAssetInfoResponse) ProtoMessage()    {}
func (*QueryAssetInfoResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_4785ee6dd031b7c8, []int{1}
}
func (m *QueryAssetInfoResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryAssetInfoResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryAssetInfoResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryAssetInfoResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryAssetInfoResponse.Merge(m, src)
}
func (m *QueryAssetInfoResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryAssetInfoResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryAssetInfoResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryAssetInfoResponse proto.InternalMessageInfo

func (m *QueryAssetInfoResponse) GetAsset() *Asset {
	if m != nil {
		return m.Asset
	}
	return nil
}

// QueryAllAssetInfosRequest is the request type for the Query/AllAssetInfos RPC method
type QueryAllAssetInfosRequest struct {
}

func (m *QueryAllAssetInfosRequest) Reset()         { *m = QueryAllAssetInfosRequest{} }
func (m *QueryAllAssetInfosRequest) String() string { return proto.CompactTextString(m) }
func (*QueryAllAssetInfosRequest) ProtoMessage()    {}
func (*QueryAllAssetInfosRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_4785ee6dd031b7c8, []int{2}
}
func (m *QueryAllAssetInfosRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryAllAssetInfosRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryAllAssetInfosRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryAllAssetInfosRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryAllAssetInfosRequest.Merge(m, src)
}
func (m *QueryAllAssetInfosRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryAllAssetInfosRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryAllAssetInfosRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryAllAssetInfosRequest proto.InternalMessageInfo

// QueryAllAssetInfosResponse is the response type for the Query/AllAssetInfos RPC method
type QueryAllAssetInfosResponse struct {
	Assets []Asset `protobuf:"bytes,1,rep,name=assets,proto3" json:"assets"`
}

func (m *QueryAllAssetInfosResponse) Reset()         { *m = QueryAllAssetInfosResponse{} }
func (m *QueryAllAssetInfosResponse) String() string { return proto.CompactTextString(m) }
func (*QueryAllAssetInfosResponse) ProtoMessage()    {}
func (*QueryAllAssetInfosResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_4785ee6dd031b7c8, []int{3}
}
func (m *QueryAllAssetInfosResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryAllAssetInfosResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryAllAssetInfosResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryAllAssetInfosResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryAllAssetInfosResponse.Merge(m, src)
}
func (m *QueryAllAssetInfosResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryAllAssetInfosResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryAllAssetInfosResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryAllAssetInfosResponse proto.InternalMessageInfo

func (m *QueryAllAssetInfosResponse) GetAssets() []Asset {
	if m != nil {
		return m.Assets
	}
	return nil
}

func init() {
	proto.RegisterType((*QueryAssetInfoRequest)(nil), "songwongtp.asset.asset.QueryAssetInfoRequest")
	proto.RegisterType((*QueryAssetInfoResponse)(nil), "songwongtp.asset.asset.QueryAssetInfoResponse")
	proto.RegisterType((*QueryAllAssetInfosRequest)(nil), "songwongtp.asset.asset.QueryAllAssetInfosRequest")
	proto.RegisterType((*QueryAllAssetInfosResponse)(nil), "songwongtp.asset.asset.QueryAllAssetInfosResponse")
}

func init() { proto.RegisterFile("asset/query.proto", fileDescriptor_4785ee6dd031b7c8) }

var fileDescriptor_4785ee6dd031b7c8 = []byte{
	// 403 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x52, 0xbf, 0xef, 0xd2, 0x40,
	0x14, 0xef, 0xa1, 0x10, 0x39, 0xe3, 0xe0, 0x05, 0x09, 0x56, 0x2d, 0x4d, 0x27, 0x62, 0x42, 0x2f,
	0xc0, 0x60, 0xa2, 0x93, 0x6c, 0x0c, 0x0e, 0x76, 0xd3, 0xed, 0x8a, 0xe7, 0xd1, 0x04, 0xee, 0x15,
	0xee, 0x50, 0x89, 0x71, 0x71, 0x72, 0x34, 0xd1, 0xc1, 0x91, 0x7f, 0xc3, 0xff, 0x80, 0x91, 0xc4,
	0xc5, 0xc9, 0x18, 0x70, 0xf0, 0xcf, 0x30, 0xbd, 0xbb, 0x60, 0xf8, 0xa6, 0x7c, 0x7f, 0x2c, 0xcd,
	0xeb, 0x7b, 0x9f, 0x5f, 0xef, 0xb5, 0xf8, 0x36, 0x53, 0x8a, 0x6b, 0x3a, 0x5f, 0xf2, 0xc5, 0x2a,
	0xce, 0x17, 0xa0, 0x81, 0x34, 0x15, 0x48, 0xf1, 0x16, 0xa4, 0xd0, 0x79, 0x6c, 0xa6, 0xf6, 0xe9,
	0x37, 0x04, 0x08, 0x30, 0x10, 0x5a, 0x54, 0x16, 0xed, 0xdf, 0x17, 0x00, 0x62, 0xca, 0x29, 0xcb,
	0x33, 0xca, 0xa4, 0x04, 0xcd, 0x74, 0x06, 0x52, 0xb9, 0xe9, 0xc3, 0x31, 0xa8, 0x19, 0x28, 0x9a,
	0x32, 0xc5, 0xad, 0x09, 0x7d, 0xd3, 0x4b, 0xb9, 0x66, 0x3d, 0x9a, 0x33, 0x91, 0x49, 0x03, 0x76,
	0x58, 0x17, 0xc5, 0x5a, 0x9a, 0x56, 0xf4, 0x08, 0xdf, 0x79, 0x5e, 0x90, 0x9e, 0x16, 0xbd, 0x91,
	0x7c, 0x0d, 0x09, 0x9f, 0x2f, 0xb9, 0xd2, 0xa4, 0x81, 0xab, 0xaf, 0xb8, 0x84, 0x59, 0x0b, 0x85,
	0xa8, 0x53, 0x4f, 0xec, 0xcb, 0xe3, 0x1b, 0x9f, 0xd6, 0x6d, 0xef, 0xef, 0xba, 0xed, 0x45, 0xcf,
	0x70, 0xf3, 0x2c, 0x51, 0xe5, 0x20, 0x15, 0x27, 0x03, 0x5c, 0x35, 0x0e, 0x86, 0x79, 0xb3, 0xff,
	0x20, 0x2e, 0xdf, 0x36, 0x36, 0xcc, 0xc4, 0x62, 0xa3, 0x7b, 0xf8, 0xae, 0x95, 0x9b, 0x4e, 0x0f,
	0x8a, 0xca, 0x65, 0x89, 0x5e, 0x60, 0xbf, 0x6c, 0xe8, 0xfc, 0x9e, 0xe0, 0x9a, 0xd1, 0x50, 0x2d,
	0x14, 0x5e, 0xbb, 0xd0, 0x70, 0x78, 0x7d, 0xf3, 0xab, 0xed, 0x25, 0x8e, 0xd2, 0xff, 0x5e, 0xc1,
	0x55, 0xa3, 0x4d, 0xbe, 0x22, 0x5c, 0x3f, 0xa8, 0x93, 0xee, 0x29, 0x91, 0xd2, 0x6b, 0xf9, 0xf1,
	0x65, 0xe1, 0x36, 0x73, 0xd4, 0xf9, 0xf8, 0xe3, 0xcf, 0x97, 0x4a, 0x44, 0x42, 0xfb, 0x31, 0xba,
	0xe3, 0x09, 0xcb, 0xa4, 0xad, 0x69, 0x56, 0x6c, 0x47, 0xdf, 0x9b, 0x83, 0x7f, 0x20, 0xdf, 0x10,
	0xbe, 0x75, 0xb4, 0x37, 0xe9, 0x9d, 0xef, 0x55, 0x72, 0x40, 0xbf, 0x7f, 0x15, 0x8a, 0x8b, 0x18,
	0x9a, 0x88, 0x3e, 0x69, 0x9d, 0x8a, 0x38, 0x1c, 0x6d, 0x76, 0x01, 0xda, 0xee, 0x02, 0xf4, 0x7b,
	0x17, 0xa0, 0xcf, 0xfb, 0xc0, 0xdb, 0xee, 0x03, 0xef, 0xe7, 0x3e, 0xf0, 0x5e, 0x52, 0x91, 0xe9,
	0xc9, 0x32, 0x8d, 0xc7, 0x30, 0xa3, 0xff, 0x9d, 0x8f, 0x84, 0xde, 0x39, 0x29, 0xbd, 0xca, 0xb9,
	0x4a, 0x6b, 0xe6, 0x6f, 0x1c, 0xfc, 0x0b, 0x00, 0x00, 0xff, 0xff, 0x72, 0x9d, 0x6a, 0x8e, 0x2d,
	0x03, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// QueryClient is the client API for Query service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type QueryClient interface {
	// AssetInfo queries the total supply and price of the provided asset
	AssetInfo(ctx context.Context, in *QueryAssetInfoRequest, opts ...grpc.CallOption) (*QueryAssetInfoResponse, error)
	// AllAssetInfos queries the total supply and price of all assets
	AllAssetInfos(ctx context.Context, in *QueryAllAssetInfosRequest, opts ...grpc.CallOption) (*QueryAllAssetInfosResponse, error)
}

type queryClient struct {
	cc grpc1.ClientConn
}

func NewQueryClient(cc grpc1.ClientConn) QueryClient {
	return &queryClient{cc}
}

func (c *queryClient) AssetInfo(ctx context.Context, in *QueryAssetInfoRequest, opts ...grpc.CallOption) (*QueryAssetInfoResponse, error) {
	out := new(QueryAssetInfoResponse)
	err := c.cc.Invoke(ctx, "/songwongtp.asset.asset.Query/AssetInfo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) AllAssetInfos(ctx context.Context, in *QueryAllAssetInfosRequest, opts ...grpc.CallOption) (*QueryAllAssetInfosResponse, error) {
	out := new(QueryAllAssetInfosResponse)
	err := c.cc.Invoke(ctx, "/songwongtp.asset.asset.Query/AllAssetInfos", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// QueryServer is the server API for Query service.
type QueryServer interface {
	// AssetInfo queries the total supply and price of the provided asset
	AssetInfo(context.Context, *QueryAssetInfoRequest) (*QueryAssetInfoResponse, error)
	// AllAssetInfos queries the total supply and price of all assets
	AllAssetInfos(context.Context, *QueryAllAssetInfosRequest) (*QueryAllAssetInfosResponse, error)
}

// UnimplementedQueryServer can be embedded to have forward compatible implementations.
type UnimplementedQueryServer struct {
}

func (*UnimplementedQueryServer) AssetInfo(ctx context.Context, req *QueryAssetInfoRequest) (*QueryAssetInfoResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AssetInfo not implemented")
}
func (*UnimplementedQueryServer) AllAssetInfos(ctx context.Context, req *QueryAllAssetInfosRequest) (*QueryAllAssetInfosResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AllAssetInfos not implemented")
}

func RegisterQueryServer(s grpc1.Server, srv QueryServer) {
	s.RegisterService(&_Query_serviceDesc, srv)
}

func _Query_AssetInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryAssetInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).AssetInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/songwongtp.asset.asset.Query/AssetInfo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).AssetInfo(ctx, req.(*QueryAssetInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_AllAssetInfos_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryAllAssetInfosRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).AllAssetInfos(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/songwongtp.asset.asset.Query/AllAssetInfos",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).AllAssetInfos(ctx, req.(*QueryAllAssetInfosRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Query_serviceDesc = grpc.ServiceDesc{
	ServiceName: "songwongtp.asset.asset.Query",
	HandlerType: (*QueryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AssetInfo",
			Handler:    _Query_AssetInfo_Handler,
		},
		{
			MethodName: "AllAssetInfos",
			Handler:    _Query_AllAssetInfos_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "asset/query.proto",
}

func (m *QueryAssetInfoRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryAssetInfoRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryAssetInfoRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Denom) > 0 {
		i -= len(m.Denom)
		copy(dAtA[i:], m.Denom)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.Denom)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryAssetInfoResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryAssetInfoResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryAssetInfoResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Asset != nil {
		{
			size, err := m.Asset.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryAllAssetInfosRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryAllAssetInfosRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryAllAssetInfosRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *QueryAllAssetInfosResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryAllAssetInfosResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryAllAssetInfosResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Assets) > 0 {
		for iNdEx := len(m.Assets) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Assets[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintQuery(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func encodeVarintQuery(dAtA []byte, offset int, v uint64) int {
	offset -= sovQuery(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *QueryAssetInfoRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Denom)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryAssetInfoResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Asset != nil {
		l = m.Asset.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryAllAssetInfosRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *QueryAllAssetInfosResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.Assets) > 0 {
		for _, e := range m.Assets {
			l = e.Size()
			n += 1 + l + sovQuery(uint64(l))
		}
	}
	return n
}

func sovQuery(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozQuery(x uint64) (n int) {
	return sovQuery(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *QueryAssetInfoRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryAssetInfoRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryAssetInfoRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Denom", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Denom = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryAssetInfoResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryAssetInfoResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryAssetInfoResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Asset", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Asset == nil {
				m.Asset = &Asset{}
			}
			if err := m.Asset.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryAllAssetInfosRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryAllAssetInfosRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryAllAssetInfosRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryAllAssetInfosResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryAllAssetInfosResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryAllAssetInfosResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Assets", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Assets = append(m.Assets, Asset{})
			if err := m.Assets[len(m.Assets)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipQuery(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthQuery
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupQuery
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthQuery
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthQuery        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowQuery          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupQuery = fmt.Errorf("proto: unexpected end of group")
)
