// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: asset/tx.proto

package types

import (
	context "context"
	fmt "fmt"
	_ "github.com/cosmos/cosmos-sdk/types/query"
	_ "github.com/gogo/protobuf/gogoproto"
	grpc1 "github.com/gogo/protobuf/grpc"
	proto "github.com/gogo/protobuf/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// MsgBuyAsset repesents a message to buy asset using uusd
type MsgBuyAsset struct {
	Address string `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty" yaml:"address"`
	Denom   string `protobuf:"bytes,2,opt,name=denom,proto3" json:"denom,omitempty"`
	Amount  uint64 `protobuf:"varint,3,opt,name=amount,proto3" json:"amount,omitempty"`
}

func (m *MsgBuyAsset) Reset()         { *m = MsgBuyAsset{} }
func (m *MsgBuyAsset) String() string { return proto.CompactTextString(m) }
func (*MsgBuyAsset) ProtoMessage()    {}
func (*MsgBuyAsset) Descriptor() ([]byte, []int) {
	return fileDescriptor_d916a3b302eb5de7, []int{0}
}
func (m *MsgBuyAsset) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgBuyAsset) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgBuyAsset.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgBuyAsset) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgBuyAsset.Merge(m, src)
}
func (m *MsgBuyAsset) XXX_Size() int {
	return m.Size()
}
func (m *MsgBuyAsset) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgBuyAsset.DiscardUnknown(m)
}

var xxx_messageInfo_MsgBuyAsset proto.InternalMessageInfo

// MsgBuyAssetResponse defines Msg/BuyAsset response type.
type MsgBuyAssetResponse struct {
}

func (m *MsgBuyAssetResponse) Reset()         { *m = MsgBuyAssetResponse{} }
func (m *MsgBuyAssetResponse) String() string { return proto.CompactTextString(m) }
func (*MsgBuyAssetResponse) ProtoMessage()    {}
func (*MsgBuyAssetResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_d916a3b302eb5de7, []int{1}
}
func (m *MsgBuyAssetResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgBuyAssetResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgBuyAssetResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgBuyAssetResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgBuyAssetResponse.Merge(m, src)
}
func (m *MsgBuyAssetResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgBuyAssetResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgBuyAssetResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgBuyAssetResponse proto.InternalMessageInfo

// MsgSellAsset represents a message to sell asset to uusd
type MsgSellAsset struct {
	Address string `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty" yaml:"address"`
	Denom   string `protobuf:"bytes,2,opt,name=denom,proto3" json:"denom,omitempty"`
	Amount  uint64 `protobuf:"varint,3,opt,name=amount,proto3" json:"amount,omitempty"`
}

func (m *MsgSellAsset) Reset()         { *m = MsgSellAsset{} }
func (m *MsgSellAsset) String() string { return proto.CompactTextString(m) }
func (*MsgSellAsset) ProtoMessage()    {}
func (*MsgSellAsset) Descriptor() ([]byte, []int) {
	return fileDescriptor_d916a3b302eb5de7, []int{2}
}
func (m *MsgSellAsset) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgSellAsset) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgSellAsset.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgSellAsset) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgSellAsset.Merge(m, src)
}
func (m *MsgSellAsset) XXX_Size() int {
	return m.Size()
}
func (m *MsgSellAsset) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgSellAsset.DiscardUnknown(m)
}

var xxx_messageInfo_MsgSellAsset proto.InternalMessageInfo

// MsgSellAssetResponse defines Msg/SellAsset response type.
type MsgSellAssetResponse struct {
}

func (m *MsgSellAssetResponse) Reset()         { *m = MsgSellAssetResponse{} }
func (m *MsgSellAssetResponse) String() string { return proto.CompactTextString(m) }
func (*MsgSellAssetResponse) ProtoMessage()    {}
func (*MsgSellAssetResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_d916a3b302eb5de7, []int{3}
}
func (m *MsgSellAssetResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgSellAssetResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgSellAssetResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgSellAssetResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgSellAssetResponse.Merge(m, src)
}
func (m *MsgSellAssetResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgSellAssetResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgSellAssetResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgSellAssetResponse proto.InternalMessageInfo

func init() {
	proto.RegisterType((*MsgBuyAsset)(nil), "songwongtp.asset.asset.MsgBuyAsset")
	proto.RegisterType((*MsgBuyAssetResponse)(nil), "songwongtp.asset.asset.MsgBuyAssetResponse")
	proto.RegisterType((*MsgSellAsset)(nil), "songwongtp.asset.asset.MsgSellAsset")
	proto.RegisterType((*MsgSellAssetResponse)(nil), "songwongtp.asset.asset.MsgSellAssetResponse")
}

func init() { proto.RegisterFile("asset/tx.proto", fileDescriptor_d916a3b302eb5de7) }

var fileDescriptor_d916a3b302eb5de7 = []byte{
	// 371 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xbc, 0x92, 0xbf, 0x6e, 0xe2, 0x40,
	0x10, 0xc6, 0xed, 0xe3, 0x8e, 0x83, 0xbd, 0x13, 0x85, 0x8f, 0x43, 0xc8, 0x3a, 0x19, 0xe4, 0xbb,
	0x02, 0x5d, 0x88, 0x57, 0x24, 0x1d, 0x5d, 0xe8, 0x52, 0xd0, 0x38, 0x5d, 0x14, 0x29, 0x5a, 0xc3,
	0x6a, 0xb1, 0x64, 0xef, 0x38, 0xcc, 0x3a, 0xc1, 0x6f, 0x90, 0x32, 0x8f, 0xc0, 0xc3, 0xa4, 0x48,
	0x49, 0x99, 0x2a, 0x8a, 0xa0, 0x49, 0x9d, 0x27, 0x88, 0xf0, 0x1f, 0xa0, 0x88, 0x22, 0xaa, 0x34,
	0xab, 0x1d, 0x7d, 0xbf, 0x9d, 0x6f, 0x66, 0x67, 0x48, 0x8d, 0x21, 0x72, 0x45, 0xd5, 0xcc, 0x89,
	0xa6, 0xa0, 0xc0, 0x68, 0x20, 0x48, 0x71, 0x03, 0x52, 0xa8, 0xc8, 0x49, 0xa5, 0xec, 0x34, 0xeb,
	0x02, 0x04, 0xa4, 0x08, 0x5d, 0xdf, 0x32, 0xda, 0xfc, 0x23, 0x00, 0x44, 0xc0, 0x29, 0x8b, 0x7c,
	0xca, 0xa4, 0x04, 0xc5, 0x94, 0x0f, 0x12, 0x73, 0xf5, 0xff, 0x08, 0x30, 0x04, 0xa4, 0x1e, 0x43,
	0x4e, 0xaf, 0x62, 0x3e, 0x4d, 0xe8, 0x75, 0xcf, 0xe3, 0x8a, 0xf5, 0x68, 0xc4, 0x84, 0x2f, 0x53,
	0x38, 0x63, 0x6d, 0x24, 0x3f, 0x86, 0x28, 0x06, 0x71, 0x72, 0xb2, 0xb6, 0x33, 0xba, 0xe4, 0x3b,
	0x1b, 0x8f, 0xa7, 0x1c, 0xb1, 0xa9, 0xb7, 0xf5, 0x4e, 0x75, 0x60, 0xbc, 0x3e, 0xb5, 0x6a, 0x09,
	0x0b, 0x83, 0xbe, 0x9d, 0x0b, 0xb6, 0x5b, 0x20, 0x46, 0x9d, 0x7c, 0x1b, 0x73, 0x09, 0x61, 0xf3,
	0xcb, 0x9a, 0x75, 0xb3, 0xc0, 0x68, 0x90, 0x32, 0x0b, 0x21, 0x96, 0xaa, 0x59, 0x6a, 0xeb, 0x9d,
	0xaf, 0x6e, 0x1e, 0xf5, 0x2b, 0xb7, 0xf3, 0x96, 0xf6, 0x32, 0x6f, 0x69, 0xf6, 0x6f, 0xf2, 0x6b,
	0xc7, 0xd4, 0xe5, 0x18, 0x81, 0x44, 0x6e, 0x2b, 0xf2, 0x73, 0x88, 0xe2, 0x8c, 0x07, 0xc1, 0x67,
	0x16, 0xd3, 0x20, 0xf5, 0x5d, 0xd7, 0xa2, 0x9a, 0xa3, 0x7b, 0x9d, 0x94, 0x86, 0x28, 0x8c, 0x0b,
	0x52, 0xd9, 0x7c, 0xcf, 0x5f, 0xe7, 0xfd, 0x31, 0x39, 0x3b, 0xed, 0x98, 0x07, 0x7b, 0x40, 0x85,
	0x8b, 0x71, 0x49, 0xaa, 0xdb, 0x86, 0xff, 0x7d, 0xf0, 0x72, 0x43, 0x99, 0xdd, 0x7d, 0xa8, 0xc2,
	0x60, 0x70, 0xfa, 0xb0, 0xb4, 0xf4, 0xc5, 0xd2, 0xd2, 0x9f, 0x97, 0x96, 0x7e, 0xb7, 0xb2, 0xb4,
	0xc5, 0xca, 0xd2, 0x1e, 0x57, 0x96, 0x76, 0x4e, 0x85, 0xaf, 0x26, 0xb1, 0xe7, 0x8c, 0x20, 0xa4,
	0xdb, 0x8c, 0x34, 0xcd, 0x75, 0x38, 0x9a, 0x30, 0x5f, 0xd2, 0x19, 0xcd, 0xd7, 0x34, 0x89, 0x38,
	0x7a, 0xe5, 0x74, 0x65, 0x8e, 0xdf, 0x02, 0x00, 0x00, 0xff, 0xff, 0xa5, 0x39, 0x71, 0xb2, 0xbc,
	0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// MsgClient is the client API for Msg service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MsgClient interface {
	// BuyAsset defines a method for buying any asset using uusd
	BuyAsset(ctx context.Context, in *MsgBuyAsset, opts ...grpc.CallOption) (*MsgBuyAssetResponse, error)
	// SellAsset defines a method for selling any asset to uusd
	SellAsset(ctx context.Context, in *MsgSellAsset, opts ...grpc.CallOption) (*MsgSellAssetResponse, error)
}

type msgClient struct {
	cc grpc1.ClientConn
}

func NewMsgClient(cc grpc1.ClientConn) MsgClient {
	return &msgClient{cc}
}

func (c *msgClient) BuyAsset(ctx context.Context, in *MsgBuyAsset, opts ...grpc.CallOption) (*MsgBuyAssetResponse, error) {
	out := new(MsgBuyAssetResponse)
	err := c.cc.Invoke(ctx, "/songwongtp.asset.asset.Msg/BuyAsset", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) SellAsset(ctx context.Context, in *MsgSellAsset, opts ...grpc.CallOption) (*MsgSellAssetResponse, error) {
	out := new(MsgSellAssetResponse)
	err := c.cc.Invoke(ctx, "/songwongtp.asset.asset.Msg/SellAsset", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MsgServer is the server API for Msg service.
type MsgServer interface {
	// BuyAsset defines a method for buying any asset using uusd
	BuyAsset(context.Context, *MsgBuyAsset) (*MsgBuyAssetResponse, error)
	// SellAsset defines a method for selling any asset to uusd
	SellAsset(context.Context, *MsgSellAsset) (*MsgSellAssetResponse, error)
}

// UnimplementedMsgServer can be embedded to have forward compatible implementations.
type UnimplementedMsgServer struct {
}

func (*UnimplementedMsgServer) BuyAsset(ctx context.Context, req *MsgBuyAsset) (*MsgBuyAssetResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method BuyAsset not implemented")
}
func (*UnimplementedMsgServer) SellAsset(ctx context.Context, req *MsgSellAsset) (*MsgSellAssetResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SellAsset not implemented")
}

func RegisterMsgServer(s grpc1.Server, srv MsgServer) {
	s.RegisterService(&_Msg_serviceDesc, srv)
}

func _Msg_BuyAsset_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgBuyAsset)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).BuyAsset(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/songwongtp.asset.asset.Msg/BuyAsset",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).BuyAsset(ctx, req.(*MsgBuyAsset))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_SellAsset_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgSellAsset)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).SellAsset(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/songwongtp.asset.asset.Msg/SellAsset",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).SellAsset(ctx, req.(*MsgSellAsset))
	}
	return interceptor(ctx, in, info, handler)
}

var _Msg_serviceDesc = grpc.ServiceDesc{
	ServiceName: "songwongtp.asset.asset.Msg",
	HandlerType: (*MsgServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "BuyAsset",
			Handler:    _Msg_BuyAsset_Handler,
		},
		{
			MethodName: "SellAsset",
			Handler:    _Msg_SellAsset_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "asset/tx.proto",
}

func (m *MsgBuyAsset) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgBuyAsset) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgBuyAsset) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Amount != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.Amount))
		i--
		dAtA[i] = 0x18
	}
	if len(m.Denom) > 0 {
		i -= len(m.Denom)
		copy(dAtA[i:], m.Denom)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Denom)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Address) > 0 {
		i -= len(m.Address)
		copy(dAtA[i:], m.Address)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Address)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgBuyAssetResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgBuyAssetResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgBuyAssetResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *MsgSellAsset) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgSellAsset) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgSellAsset) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Amount != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.Amount))
		i--
		dAtA[i] = 0x18
	}
	if len(m.Denom) > 0 {
		i -= len(m.Denom)
		copy(dAtA[i:], m.Denom)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Denom)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Address) > 0 {
		i -= len(m.Address)
		copy(dAtA[i:], m.Address)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Address)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgSellAssetResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgSellAssetResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgSellAssetResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func encodeVarintTx(dAtA []byte, offset int, v uint64) int {
	offset -= sovTx(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *MsgBuyAsset) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Address)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.Denom)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	if m.Amount != 0 {
		n += 1 + sovTx(uint64(m.Amount))
	}
	return n
}

func (m *MsgBuyAssetResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *MsgSellAsset) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Address)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.Denom)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	if m.Amount != 0 {
		n += 1 + sovTx(uint64(m.Amount))
	}
	return n
}

func (m *MsgSellAssetResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func sovTx(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozTx(x uint64) (n int) {
	return sovTx(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *MsgBuyAsset) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgBuyAsset: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgBuyAsset: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Address", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Address = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Denom", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Denom = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Amount", wireType)
			}
			m.Amount = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Amount |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgBuyAssetResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgBuyAssetResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgBuyAssetResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgSellAsset) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgSellAsset: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgSellAsset: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Address", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Address = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Denom", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Denom = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Amount", wireType)
			}
			m.Amount = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Amount |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgSellAssetResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgSellAssetResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgSellAssetResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipTx(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowTx
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTx
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTx
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthTx
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupTx
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthTx
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthTx        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowTx          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupTx = fmt.Errorf("proto: unexpected end of group")
)
